### ISSUE TITLE
Reduce the PHP requirement for 1.3.x

### ISSUE THREAD

**Issue by dantman** [triplepoint/php-units-of-measure#38]
I know you've moved on to `2.0.0`. However I think it would be fair to make a point release to `1.3.x` with the PHP requirement reduced to `5.3.2`.

The problem is Ubuntu 10.04 (which is still supported) has `PHP 5.3.2`, which is fine for `1.3.x` because the Ubuntu package is kept up to date with all the security patches in `PHP 5.3.5` and later.

**Comment by triplepoint** [comment]
To be fair, Ubuntu 10.04 is only supported for another 45 days or so.  Moreover, PHP EOL'ed 5.3 in September 2014, even for security patches, and will EOL 5.4 this September.  So on the grounds of what's supported with security patches, I don't think it's reasonable at this point to support anything below PHP 5.4.

However, the required versions for composer-managed libraries is less about enforcing security hygiene, and more about specifying with which versions the code is compatible.  It was a mistake on my part to specify down to the bugfix level which version of PHP was required for this library to function.

I'll roll a 1.3.2 version, and remove the bugfix level of specificity for the PHP version.  It will instead be "5.3.*".

**Comment by triplepoint** [comment]
Oh, wait, I wasn't thinking.  Should've been ">=5.3.0", to allow for 5.4, 5.5, etc.  Sigh, looks like the tag you want will be 1.3.3, hang on a sec.

**Comment by triplepoint** [comment]
OK tag 1.3.3 builds as expected, for all versions of PHP >= 5.3.0.

**Comment by dantman** [comment]
> To be fair, Ubuntu 10.04 is only supported for another 45 days or so.

That part is fair. I need to move more stuff for work onto the new cluster.

> Moreover, PHP EOL'ed 5.3 in September 2014, even for security patches, and will EOL 5.4 this September. So on the grounds of what's supported with security patches, I don't think it's reasonable at this point to support anything below PHP 5.4.

Debian/Ubuntu handle security patches themselves. Even though 5.3 itself is EOL, the Debian/Ubuntu packages still get security patches to them. ie: Their 5.3 is actually patched with fixes for security issues that the actual PHP maintainers only put in 5.3, 5.5, etc. (see [their changelog](http://changelogs.ubuntu.com/changelogs/pool/main/p/php5/php5_5.3.2-1ubuntu4.28/changelog))

So for as long as Debian or Ubuntu has a supported LTS release with an EOL version of PHP it's actually ok security wise to use and support that version.

**Comment by triplepoint** [comment]
Hunh, I wasn't aware Ubuntu maintained PHP on their own past the EOL designated by php.net.  That's interesting, thanks for pointing that out.  Sounds like a hell of a lot of work on Ubuntu's part.

In any case, tag v1.3.3 is open for business, let me know if there's still any issues.
